name: ''
fullname: ''

image:
  registry: docker.io
  # repository: required
  # tag: latest
  pullPolicy: IfNotPresent
  pullSecret: ""

securityContext:
  pod: {}
  container: {}

command: []

args: []

env: {}
envFrom: {}

config: {}
configMountPath: /config/config.yaml
additionalConfigs: []

# startupProbe:
#   httpGet:
#     port: http-ingress
#     path: /

# livenessProbe:
#   httpGet:
#     port: http-ingress
#     path: /

# readinessProbe:
#   httpGet:
#     port: http-ingress
#     path: /

maxShutdownSeconds: 30

labels: {}

annotations: {}

resources:
  requests:
    memory: 64Mi
    cpu: 10m
  limits:
    memory: 96Mi
    cpu: 2000m

rollout:
  controller: Deployment
  strategy: RollingUpdate
  autoPromotion: true
  flagger: false
  analysis: null

replicas: 1

autoscaling:
  enabled: false
  maxReplicas: 3
  metric:
    type: Resource
    name: cpu
    object:
    selector: {}
  targetValue: 80
  behavior: {}

nodeSelector: {}

persistence:
  enabled: false
  storageClass: ''
  accessModes: [ReadWriteOnce]
  size: 1G
  mountPath: ''  # required if enabled

secrets: {}

additionalMounts: {}

ingress:
  enabled: false
  port: 80
  protocol: http
  domains: []
  paths: []
  tls:
    enabled: false
    secret: ''
  cors:
    enabled: false
    allowOrigins: []
    allowMethods: [GET]
    allowHeaders: [Content-Type]
    allowCredentials: true
    exposeHeaders: []
  class: ''
  annotations: {}
  headless: false
  additionalSelectors: {}
  istio:
    enabled: false
    gateways: []
    httpHeaders: {}
    timeout: 15s
    retries: {}
  extra: {}

netpol:
  enabled: false
  ingress:
    # Allow from same namespace
    - from: [podSelector: {}]
  egress: []

tracing:
  enabled: false
  probability: 1
  class: ''

monitoring:
  enabled: false
  port: 9100
  path: /metrics
  interval: 1m

alerting:
  enabled: false
  labels: {}
  memory:
    maxUsageFactor: 0.9
  http:
    sampleInterval: 20m
    referenceInterval: 1w
    maxSlowdown: 2.5
    max4xxRatio: 2.5
    max5xxCount: 0
  grpc:
    requestsMetric: grpc_server_handled_total
    sampleInterval: 20m
    referenceInterval: 1w
    maxErrorRatio: 2.5
    maxCriticalErrors: 0
    criticalCodes: [Internal, Unimplemented]

sidecars: []

rbac:
  roles: []
  clusterRoles: []

global:
  grafana:
    url: ''
    dashboard: qqsCbY5Zz
