{{- if and .Values.monitoring.enabled .Values.alerting.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}
    prometheus: cluster
    role: alert-rules

spec:
  groups:
    - name: {{ include "generic-service.fullname" . }}.rules
      rules:
        - alert: Down
          expr: kube_deployment_status_replicas_available{namespace="{{ .Release.Namespace }}", deployment="{{ include "generic-service.fullname" . }}"} == 0
          for: '{{ if .Values.ingress.enabled }}1m{{ else }}5m{{ end }}'
          labels:
            component: {{ include "generic-service.fullname" . }}
            severity: critical
{{- if .Values.alerting.labels }}{{ toYaml .Values.alerting.labels | nindent 12 }}{{ end }}
          annotations:
            summary: '{{ include "generic-service.fullname" . }} is down.'
            description: 'All replicas for {{ include "generic-service.fullname" . }} are down.'

{{- if gt .Values.replicas 1.0 }}
        - alert: ReplicasDown
          expr: kube_deployment_status_replicas_unavailable{namespace="{{ .Release.Namespace }}", deployment="{{ include "generic-service.fullname" . }}"} > 0
          for: 10m
          labels:
            component: {{ include "generic-service.fullname" . }}
            severity: warning
{{- if .Values.alerting.labels }}{{ toYaml .Values.alerting.labels | nindent 12 }}{{ end }}
          annotations:
            summary: '{{ include "generic-service.fullname" . }} replicas are down.'
            description: '{{"{{ $value }}"}} replicas for {{ include "generic-service.fullname" . }} are down.'
{{- end }}

        - alert: MemoryUsageAboveRequest
          expr: |
            max(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}"}) -
            min(kube_pod_container_resource_requests{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}", resource="memory"})
            > 0
          for: 10m
          labels:
            component: {{ include "generic-service.fullname" . }}
            severity: warning
{{- if .Values.alerting.labels }}{{ toYaml .Values.alerting.labels | nindent 12 }}{{ end }}
          annotations:
            summary: '{{ include "generic-service.fullname" . }} using more memory than requested.'
            description: '{{ include "generic-service.fullname" . }} is using {{"{{ $value | humanize1024 }}"}}B more than its requested memory ({{ .Values.resources.requests.memory }}B).'

        - alert: MemoryUsageCloseToLimit
          expr: |
            max(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}"}) /
            min(kube_pod_container_resource_limits{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}", resource="memory"})
            > {{ .Values.alerting.memoryUsage.thresholdFactor }}
          labels:
            component: {{ include "generic-service.fullname" . }}
            severity: critical
{{- if .Values.alerting.labels }}{{ toYaml .Values.alerting.labels | nindent 12 }}{{ end }}
          annotations:
            summary: '{{ include "generic-service.fullname" . }} memory usage is close to its limit.'
            description: '{{ include "generic-service.fullname" . }} is using {{"{{ $value | humanizePercentage }}"}} of its memory limit ({{ .Values.resources.limits.memory }}B).'

{{ if .Values.ingress.istio.enabled }}
        - alert: Http5xxResponses
          expr: ceil(sum(increase(istio_requests_total{ {{ include "generic-service.istio-filter" . }}, response_code=~"5.." }[1m]))) > 0
          labels:
            component: {{ include "generic-service.fullname" . }}
            severity: warning
{{- if .Values.alerting.labels }}{{ toYaml .Values.alerting.labels | nindent 12 }}{{ end }}
          annotations:
            summary: '{{ include "generic-service.fullname" . }} gave HTTP 5xx responses.'
            description: '{{ include "generic-service.fullname" . }} gave {{"{{ $value }}"}} HTTP 5xx responses in the last minute.'

        - alert: HighHttp4xxRatio
          expr: |
            sum(rate(istio_requests_total{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.http4xxRatio.sampleInterval }}])) > 0 and
            (sum(rate(istio_requests_total{ {{ include "generic-service.istio-filter" . }}, response_code=~"4.." }[{{ .Values.alerting.http4xxRatio.sampleInterval }}])) / sum(rate(istio_requests_total{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.http4xxRatio.sampleInterval }}]))) /
            (sum(rate(istio_requests_total{ {{ include "generic-service.istio-filter" . }}, response_code=~"4.." }[{{ .Values.alerting.http4xxRatio.referenceInterval }}])) / sum(rate(istio_requests_total{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.http4xxRatio.referenceInterval }}]))) >
            {{ .Values.alerting.http4xxRatio.thresholdFactor }}
          labels:
            component: {{ include "generic-service.fullname" . }}
            severity: info
{{- if .Values.alerting.labels }}{{ toYaml .Values.alerting.labels | nindent 12 }}{{ end }}
          annotations:
            summary: '{{ include "generic-service.fullname" . }} gave more HTTP 4xx responses than usual.'
            description: '{{ include "generic-service.fullname" . }} gave {{"{{$value}}"}}x more HTTP 4xx responses in the last {{ .Values.alerting.http4xxRatio.sampleInterval }} than in the last {{ .Values.alerting.http4xxRatio.referenceInterval }}.'

        - alert: SlowResponseTime
          expr: |
            sum(increase(istio_requests_total{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.responseTime.sampleInterval }}])) > 0 and
            (sum(increase(istio_request_duration_seconds_sum{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.responseTime.sampleInterval }}])) / sum(increase(istio_requests_total{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.responseTime.sampleInterval }}]))) /
            (sum(increase(istio_request_duration_seconds_sum{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.responseTime.referenceInterval }}])) / sum(increase(istio_requests_total{ {{ include "generic-service.istio-filter" . }} }[{{ .Values.alerting.responseTime.referenceInterval }}]))) >
            {{ .Values.alerting.responseTime.thresholdFactor }}
          labels:
            component: {{ include "generic-service.fullname" . }}
            severity: info
{{- if .Values.alerting.labels }}{{ toYaml .Values.alerting.labels | nindent 12 }}{{ end }}
          annotations:
            summary: '{{ include "generic-service.fullname" . }} HTTP responses are slower than usual.'
            description: '{{ include "generic-service.fullname" . }} HTTP responses are {{"{{$value}}"}}x slower in the last {{ .Values.alerting.responseTime.sampleInterval }} than in the last {{ .Values.alerting.responseTime.referenceInterval }}.'
{{- end }}

{{- end }}
