{{- if and (and .Values.alerting.enabled (or .Values.alerting.logs.levels .Values.alerting.logs.custom)) (or .Values.alerting.logs.createLokiRule .Values.alerting.logs.lokiConfigMap) }}

{{- if .Values.alerting.logs.createLokiRule }}
apiVersion: logging.opsgy.com/v1beta1
kind: LokiRule
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{- include "generic-service.top-level-labels" . | nindent 4 }}

spec:
{{- else }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service.fullname" . }}-loki-rules
  labels: {{- include "generic-service.top-level-labels" . | nindent 4 }}
    {{ .Values.alerting.logs.lokiConfigMap.label }}: {{ .Values.alerting.logs.lokiConfigMap.labelValue | quote }}

data:
  '{{ .Release.Namespace }}.{{ .Release.Name }}.yaml': |
{{- end }}
    groups:
      - name: {{ include "generic-service.fullname" . }}.logs
        rules:
          {{- range $level, $options := .Values.alerting.logs.levels }}
          - alert: LogMessages{{ $level | title }}
            expr: sum(count_over_time(({namespace="{{ $.Release.Namespace }}", container="{{ include "generic-service.fullname" $ }}", {{ $.Values.alerting.logs.levelLabel }}="{{ $level }}"})[{{ $.Values.alerting.logs.countInterval }}])) > {{ $options.maxCount | default 0 }}
            for: 1s
            labels: {{- include "generic-service.alert-labels" $ | nindent 14 }} {{ $options.severity | default "warning" }}
              topic: logs
            annotations: {{- include "generic-service.alert-annotations" $ | nindent 14 }} {{ $level }} logs
              description: '{{ $.Release.Name }} reported {{"{{ $value }}"}} {{ $level }} log messages in the last {{ $.Values.alerting.logs.countInterval }}.'
          {{- end }}

        {{- range $name, $props := .Values.alerting.logs.custom }}
          - alert: {{ $name | quote }}
            expr: |
              sum(
                count_over_time(
                  ({
                    namespace="{{ $.Release.Namespace }}", container="{{ include "generic-service.fullname" $ }}"{{ if $props.labelMatchers }}, {{ tpl $props.labelMatchers $ }}{{ end }}
                  } |~ {{ $props.regex | quote }})
                [{{ $props.countInterval | default $.Values.alerting.logs.countInterval }}])
              )
              {{ $props.predicate | required "alert predicate required" }}
            for: 1s
            labels: {{- include "generic-service.alert-labels" $ | nindent 14 }} {{ $props.severity | default "warning" }}
              topic: {{ $props.topic | default "logs" }}
            annotations: {{- include "generic-service.alert-annotations" $ | nindent 14 }} {{ $props.summary | required "alert summary required" }}
              description: {{ $props.description | required "alert description required" | quote }}
        {{- end }}
{{- end }}
