{{- if .Values.alerting.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}
    prometheus: cluster
    role: alert-rules

spec:
  groups:
    - name: {{ include "generic-service.fullname" . }}.rules
      rules:
      {{- if ne .Values.rollout.controller "ArgoRollout" }}
        - alert: Down
          expr: kube_{{ .Values.rollout.controller | lower }}_status_{{ if eq .Values.rollout.controller "DaemonSet" }}number{{ else }}replicas{{ end }}_ready{namespace="{{ .Release.Namespace }}", {{ .Values.rollout.controller | lower }}="{{ include "generic-service.fullname" . }}"} == 0
          for: '{{ if .Values.ingress.enabled }}1m{{ else }}5m{{ end }}'
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} critical
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} down
            description: 'All replicas for {{ include "generic-service.fullname" . }} are down.'

        {{- if or (gt .Values.replicas 1.0) (eq .Values.rollout.controller "DaemonSet") }}
        - alert: ReplicasDown
          expr: |
            {{- if eq .Values.rollout.controller "StatefulSet" }}
            kube_statefulset_status_replicas{namespace="{{ .Release.Namespace }}", statefulset="{{ include "generic-service.fullname" . }}"} - kube_statefulset_status_replicas_ready{namespace="{{ .Release.Namespace }}", statefulset="{{ include "generic-service.fullname" . }}"} > 0
            {{- else }}
            kube_{{ .Values.rollout.controller | lower }}_status_{{ if eq .Values.rollout.controller "DaemonSet" }}number{{ else }}replicas{{ end }}_unavailable{namespace="{{ .Release.Namespace }}", {{ .Values.rollout.controller | lower }}="{{ include "generic-service.fullname" . }}"} > 0
            {{- end }}
          for: 10m
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} warning
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} replicas down
            description: '{{"{{ $value }}"}} replicas for {{ include "generic-service.fullname" . }} are down.'
        {{- end }}
      {{- end }}

        - alert: MemoryUsageAboveRequest
          expr: |
            max(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}"}) by (pod) -
            min(kube_pod_container_resource_requests{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}", resource="memory"}) by (pod)
            > 0
          for: 10m
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} warning
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} using more memory than requested
            description: '{{"{{ $labels.pod }}"}} is using {{"{{ humanize1024 $value }}"}}B more than its requested memory ({{ .Values.resources.requests.memory }}B).'

        - alert: MemoryUsageCloseToLimit
          expr: |
            max(container_memory_working_set_bytes{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}"}) by (pod) /
            min(kube_pod_container_resource_limits{namespace="{{ .Release.Namespace }}", container="{{ include "generic-service.fullname" . }}", resource="memory"}) by (pod)
            > {{ .Values.alerting.memory.maxUsageFactor }}
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} critical
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} memory usage close to limit
            description: '{{"{{ $labels.pod }}"}} is using {{"{{ humanizePercentage $value }}"}} of its memory limit ({{ .Values.resources.limits.memory }}B).'

      {{- if .Values.ingress.enabled }}
        {{- if or .Values.ingress.istio.enabled (eq .Values.ingress.class "nginx") }}
        {{- if .Values.alerting.http.referenceInterval }}
        - alert: HttpSlowdown
          expr: |
            (sum(increase({{ include "generic-service.request-duration-metric" . }}[{{ .Values.alerting.http.sampleInterval }}])) / sum(increase({{ include "generic-service.request-count-metric" . }}[{{ .Values.alerting.http.sampleInterval }}]))) /
            (sum(increase({{ include "generic-service.request-duration-metric" . }}[{{ .Values.alerting.http.referenceInterval }}])) / sum(increase({{ include "generic-service.request-count-metric" . }}[{{ .Values.alerting.http.referenceInterval }}])))
            > {{ .Values.alerting.http.maxSlowdown }}
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} info
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} HTTP responses slower than usual
            description: '{{ include "generic-service.fullname" . }} HTTP responses are {{"{{ $value }}"}}x slower in the last {{ .Values.alerting.http.sampleInterval }} than in the last {{ .Values.alerting.http.referenceInterval }}.'

        - alert: Http4xx
          expr: |
            (sum(rate({{ include "generic-service.request-code-count-metric" . }}"4.."}[{{ .Values.alerting.http.sampleInterval }}])) / sum(rate({{ include "generic-service.request-count-metric" . }}[{{ .Values.alerting.http.sampleInterval }}]))) /
            (sum(rate({{ include "generic-service.request-code-count-metric" . }}"4.."}[{{ .Values.alerting.http.referenceInterval }}])) / sum(rate({{ include "generic-service.request-count-metric" . }}[{{ .Values.alerting.http.referenceInterval }}])))
            > {{ .Values.alerting.http.max4xxRatio }}
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} warning
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} higher HTTP 4xx rate
            description: '{{ include "generic-service.fullname" . }} gave {{"{{ $value }}"}}x more HTTP 4xx responses per request in the last {{ .Values.alerting.http.sampleInterval }} than in the last {{ .Values.alerting.http.referenceInterval }}.'
        {{- end }}

        - alert: Http5xx
          expr: |
            sum(round(increase({{ include "generic-service.request-code-count-metric" . }}"5.."}[{{ .Values.alerting.http.sampleInterval }}])))
            > {{ .Values.alerting.http.max5xxCount }}
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} critical
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} HTTP 5xx responses
            description: '{{ include "generic-service.fullname" . }} gave {{"{{ $value }}"}} HTTP 5xx responses in the last {{ .Values.alerting.http.sampleInterval }}.'
        {{- end }}

        {{- if eq .Values.ingress.protocol "grpc" }}
        {{- if .Values.alerting.grpc.referenceInterval }}
        - alert: GrpcErrors
          expr: |
            (sum(rate({{ .Values.alerting.grpc.requestsMetric }}{namespace="{{ .Release.Namespace }}",release="{{ .Release.Name }}",grpc_code!="OK"}[{{ .Values.alerting.grpc.sampleInterval }}])) / sum(rate({{ .Values.alerting.grpc.requestsMetric }}{namespace="{{ .Release.Namespace }}",release="{{ .Release.Name }}"}[{{ .Values.alerting.grpc.sampleInterval }}]))) /
            (sum(rate({{ .Values.alerting.grpc.requestsMetric }}{namespace="{{ .Release.Namespace }}",release="{{ .Release.Name }}",grpc_code!="OK"}[{{ .Values.alerting.grpc.referenceInterval }}])) / sum(rate({{ .Values.alerting.grpc.requestsMetric }}{namespace="{{ .Release.Namespace }}",release="{{ .Release.Name }}"}[{{ .Values.alerting.grpc.referenceInterval }}])))
            > {{ .Values.alerting.grpc.maxErrorRatio }}
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} warning
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} higher gRPC error rate
            description: '{{ include "generic-service.fullname" . }} gave {{"{{ $value }}"}}x more gRPC error responses per request in the last {{ .Values.alerting.grpc.sampleInterval }} than in the last {{ .Values.alerting.grpc.referenceInterval }}.'
        {{- end }}

        - alert: GrpcCriticalErrors
          expr: |
            round(sum(increase({{ .Values.alerting.grpc.requestsMetric }}{namespace="{{ .Release.Namespace }}", release="{{ .Release.Name }}", grpc_code=~"{{ .Values.alerting.grpc.criticalCodes | join "|" }}"}[{{ .Values.alerting.grpc.sampleInterval }}])) by (grpc_code))
            > {{ .Values.alerting.grpc.maxCriticalErrors | int }}
          labels: {{ include "generic-service.alert-labels" . | nindent 12 }} critical
          annotations: {{ include "generic-service.alert-annotations" . | nindent 12 }} critical gRPC errors
            description: '{{ include "generic-service.fullname" . }} returned {{"{{ $value }}"}} gRPC errors with status code {{"{{ $labels.grpc_code }}"}} in the last {{ .Values.alerting.grpc.sampleInterval }}.'
        {{- end }}
      {{- end }}

{{- end }}
