{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{- include "generic-service.top-level-labels" . | nindent 4 }}

data:
  data.yaml: | {{- .Values.config | toPrettyJson | nindent 4 }}
{{- end }}
