{{- if and (and .Values.ingress.enabled .Values.ingress.domains) (not .Values.ingress.istio.enabled) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{- include "generic-service.default-labels" . | nindent 4 }}
  annotations:
  {{- if eq .Values.ingress.class "nginx" }}
    nginx.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.protocol | upper }}
    {{- if .Values.ingress.cors.enabled }}
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    {{ if .Values.ingress.cors.allowOrigins }}nginx.ingress.kubernetes.io/cors-allow-origin: {{ join "," .Values.ingress.cors.allowOrigins | quote }}{{ end }}
    {{ if .Values.ingress.cors.allowMethods }}nginx.ingress.kubernetes.io/cors-allow-methods: {{ join "," .Values.ingress.cors.allowMethods | quote }}{{ end }}
    {{ if .Values.ingress.cors.allowHeaders }}nginx.ingress.kubernetes.io/cors-allow-headers: {{ join "," .Values.ingress.cors.allowHeaders | quote }}{{ end }}
    nginx.ingress.kubernetes.io/cors-allow-credentials: {{ .Values.ingress.cors.allowCredentials | quote }}
    {{ if .Values.ingress.cors.exposeHeaders }}nginx.ingress.kubernetes.io/cors-expose-headers: {{ join "," .Values.ingress.cors.exposeHeaders | quote }}{{ end }}
    {{- end }}
  {{- end }}
  {{- if .Values.ingress.annotations }}  
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}

spec:
  {{- if .Values.ingress.class }}
  ingressClassName: {{ .Values.ingress.class }}
  {{- end }}

  {{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ tpl .Values.ingress.tls.secret . }}
      hosts: {{- .Values.ingress.domains | toYaml | nindent 8 }}
  {{- end }}

  rules:
    {{- range .Values.ingress.domains }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range ($.Values.ingress.paths | default (list "/")) }}
          - pathType: Prefix
            path: {{ . | quote }}
            backend:
              service:
                name: {{ include "generic-service.fullname" $ }}
                port:
                  name: {{ $.Values.ingress.protocol }}-ingress
          {{- end }}
    {{- end }}

{{- end }}
