{{- if and (and .Values.ingress.enabled .Values.ingress.extra) (not .Values.ingress.istio.enabled) }}
{{- range $name, $extra := .Values.ingress.extra }}
{{- if $extra.domains }}
{{ $class := $extra.class | default $.Values.ingress.class }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "generic-service.fullname" $ }}-{{ $name }}
  labels: {{- include "generic-service.default-labels" $ | nindent 4 }}
  annotations:
  {{- if eq $class "nginx" }}
    nginx.ingress.kubernetes.io/backend-protocol: {{ if $extra.port }}{{ $extra.protocol | default "http" | upper }}{{ else }}{{ $.Values.ingress.protocol | upper }}{{ end }}
  {{- end }}
  {{- if $.Values.ingress.annotations }}
    {{- if $extra.annotations }}
      {{- $merged := deepCopy $.Values.ingress.annotations | mustMerge $extra.annotations }}
      {{- range $mname, $mvalue := $merged }}
        {{- if ne $mvalue "nil" }}
          {{- dict $mname $mvalue | toYaml | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- else }}
      {{- $.Values.ingress.annotations | toYaml | nindent 4 }}
    {{- end }}
  {{- else if $extra.annotations }}
    {{- $extra.annotations | toYaml | nindent 4 }}
  {{- end }}

spec:
  {{- if $class }}
  ingressClassName: {{ $class }}
  {{- end }}

  {{- if $extra.tls }}{{ if $extra.tls.enabled }}
  tls:
    - secretName: {{ $extra.tls.secret | default (printf "%s-%s-tls" $.Release.Name $name) }}
      hosts: {{- $extra.domains | toYaml | nindent 8 }}
  {{- end }}{{ end }}

  rules:
    {{- range $extra.domains }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- range ($extra.paths | default (list "/")) }}
          - pathType: Prefix
            path: {{ . | quote }}
            backend:
              service:
                name: {{ include "generic-service.fullname" $ }}
                port:
                {{- if $extra.port }}
                  name: {{ $extra.protocol | default "http" }}-{{ $name }}
                {{- else }}
                  {{- if $extra.protocol }}
                    {{ fail "ingress.extra.*.protocol may not be set if ingress.extra.*.port is not set" }}
                  {{- end }}
                  name: {{ $.Values.ingress.protocol }}-ingress
                {{- end }}
            {{- end }}
      {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
