{{- if and (and .Values.ingress.enabled .Values.ingress.domains) (not .Values.ingress.istio.enabled) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.class }}
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- end }}
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}

spec:
{{- if .Values.ingress.tls.enabled }}
  tls:
    - secretName: {{ .Values.ingress.tls.secret | default (printf "%s-tls" .Release.Name) }}
      hosts: {{ .Values.ingress.domains | toYaml | nindent 8 }}
{{- end }}
  rules:
    {{- $root := . -}}
    {{- range .Values.ingress.domains }}
    - host: {{ . | quote }}
      http:
        paths:
        {{- range ($root.Values.ingress.paths | default (list "/")) }}
          - pathType: Prefix
            path: {{ . | quote }}
            backend:
              service:
                name: {{ include "generic-service.fullname" $root }}
                port:
                  name: {{ $root.Values.ingress.protocol }}-ingress
        {{- end }}
      {{- end }}

{{- end }}
