{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}

spec:
  selector:
    matchLabels: {{ include "generic-service.selector-labels" . | nindent 6 }}

  podMetricsEndpoints:
    - port: {{ if and .Values.ingress.enabled (eq .Values.monitoring.port .Values.ingress.port) }}http-ingress{{ else }}http-monitoring{{ end }}
      path: {{ .Values.monitoring.path | quote }}
      interval: {{ .Values.monitoring.interval | quote }}

  podTargetLabels:
    - app
    - release
    {{- if eq .Values.rollout.controller "ArgoRollout" }}
    - role
    {{- end }}

{{- end }}
