{{- if .Values.monitoring.enabled }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}

spec:
  selector:
    matchLabels: {{ include "generic-service.selector-labels" . | nindent 6 }}
      monitoring: "true"

  endpoints:
    - port: http-monitoring
      path: {{ .Values.monitoring.path | quote }}
      interval: {{ .Values.monitoring.interval | quote }}

  targetLabels:
    - app
    - release
    {{- if eq .Values.rollout.controller "ArgoRollout" }}
    - role
    {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-service.fullname" . }}-monitoring
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}
    monitoring: "true"

spec:
  selector: {{ include "generic-service.selector-labels" . | nindent 4 }}

  clusterIP: None
  publishNotReadyAddresses: true

  ports:
    - name: http-monitoring
      port: 9100
      targetPort: {{ .Values.monitoring.port }}

{{- end }}
