{{- if and .Values.ingress.enabled (gt .Values.replicas 1.0) }}

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{- include "generic-service.top-level-labels" . | nindent 4 }}

spec:
  minAvailable: 1

  selector:
    matchLabels: {{- include "generic-service.selector-labels" . | nindent 6 }}

{{- end }}
