{{- if or (kindIs "string" .Values.scheduling.minAvailable) (and (gt .Values.scheduling.minAvailable 0.0) (lt .Values.scheduling.minAvailable .Values.replicas)) }}

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{- include "generic-service.top-level-labels" . | nindent 4 }}

spec:
  minAvailable: {{ .Values.scheduling.minAvailable }}

  selector:
    matchLabels: {{- include "generic-service.selector-labels" . | nindent 6 }}

{{- end }}
