{{- if and .Values.persistence.enabled (ne .Values.rollout.controller "StatefulSet") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{- include "generic-service.top-level-labels" . | nindent 4 }}

spec:
  {{- with .Values.persistence.storageClass }}
  storageClassName: '{{ . }}'
  {{- end }}
  accessModes: {{- .Values.persistence.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: '{{ .Values.persistence.size }}'
{{- end }}
