{{- range $name, $secret := .Values.secrets }}
{{- if $secret.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $name $ }}
type: Opaque
data:
  {{- range $key, $val := $secret.files }}
  {{ $key | quote }}: {{ $val }}
  {{- end }}
---
{{- end }}
{{- end }}
