{{- if and .Values.ingress.enabled (not .Values.rollout.flagger) }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}
{{- if eq .Values.ingress.class "contour" }}
  annotations:
    projectcontour.io/upstream-protocol.h2c: grpc-ingress{{ range $name, $_ := .Values.ingress.extra }},grpc-{{ $name }}{{ end }}
    projectcontour.io/upstream-protocol.h2: grpcs-ingress{{ range $name, $_ := .Values.ingress.extra }},grpcs-{{ $name }}{{ end }}
    projectcontour.io/upstream-protocol.tls: https-ingress{{ range $name, $_ := .Values.ingress.extra }},https-{{ $name }}{{ end }}
{{- end }}

spec:
  selector: {{ include "generic-service.selector-labels" . | nindent 4 }}
  {{- if .Values.ingress.additionalSelectors }}
  {{- .Values.ingress.additionalSelectors | toYaml | nindent 4 }}
  {{- end }}

  {{- if .Values.ingress.headless }}
  clusterIP: None
  {{- end }}

  ports:
    - name: '{{ .Values.ingress.protocol }}-ingress'
      port: 80
      targetPort: {{ .Values.ingress.port }}
    {{- range $name, $extra := .Values.ingress.extra }}
    {{- if $extra.port }}
    - name: {{ $extra.protocol | default "http" }}-{{ $name }}
      port: {{ $extra.port }}
      targetPort: {{ $extra.port }}
    {{- end }}
    {{- end }}

{{- if eq .Values.rollout.controller "ArgoRollout" }}
---
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "generic-service.fullname" . }}-preview'
  labels: {{ include "generic-service.default-labels" . | nindent 4 }}

spec:
  selector: {{ include "generic-service.selector-labels" . | nindent 4 }}
  {{- if .Values.ingress.additionalSelectors }}
  {{- .Values.ingress.additionalSelectors | toYaml | nindent 4 }}
  {{- end }}

  {{- if .Values.ingress.headless }}
  clusterIP: None
  {{- end }}

  ports:
    - name: '{{ .Values.ingress.protocol }}-ingress'
      port: 80
      targetPort: {{ .Values.ingress.port }}
{{- end }}

{{- end }}
