# Argo Rollout controller test

image:
  repository: jwilder/whoami
  tag: latest

ingress:
  enabled: true
  port: 8000

rollout:
  controller: ArgoRollout
  strategy: BlueGreen
  autoPromotion: true
