# Ingress test

image:
  registry: docker.io
  repository: jwilder/whoami
  tag: latest

ingress:
  enabled: true
  port: 8000

livenessProbe:
  httpGet:
    port: http-ingress
    path: /

readinessProbe:
  httpGet:
    port: http-ingress
    path: /
