# Extra ingress test

image:
  repository: jwilder/whoami
  tag: latest

ingress:
  enabled: true
  port: 8000
  domains: ['example.com']
  class: nginx
  extra:
    additional-annotation:
      domains: ['custom-annotation.example.com']
      annotations:
        key: value
    other-port:
      port: 1337
      domains: ['custom-port.example.com']
