# Ingress test

image:
  repository: jwilder/whoami
  tag: latest

ingress:
  enabled: true
  port: 8000
  domains: ['example.com']
  class: nginx
  cors:
    enabled: true

livenessProbe:
  httpGet:
    port: http-ingress
    path: /

readinessProbe:
  httpGet:
    port: http-ingress
    path: /
