# RBAC test

image:
  repository: jwilder/whoami
  tag: latest
rbac:
  clusterRoles: [view]
  customRoles:
    get-my-map:
      - apiGroups: [""]
        resources: [configmaps]
        resourceNames: [my-configmap]
        verbs: [get]
