# Pod and node affinity test

image:
  repository: jwilder/whoami
  tag: latest


scheduling:
  nodePreferences:
    someKey: [someValue1, someValue2]
  nodeExclusions:
    otherKey: [otherValue1, otherValue2]
  podAffinity:
    someKey: someValue
