# Pod and node affinity test

image:
  repository: jwilder/whoami
  tag: latest

scheduling:
  priority: system-cluster-critical
  nodePreferences:
    someKey: [someValue1, someValue2]
  nodeExclusions:
    otherKey: [otherValue1, otherValue2]
  tolerations: [someTaint]
  podAffinity:
    someKey: someValue
  podAntiAffinity:
    otherKey: otherValue
  replicaSpread: Strict
